#!/usr/bin/env bash

set -Eeu

# Environment variables set by other scripts
# Strings will be replaced by test.sh , PKGBUILD or other packaging script
QctlLibDir="%LIB_DIR%"
DataDir="%DATA_DIR%"

LoadShells=("${QctlLibDir}/main.sh")

# Load main library
for file in "${LoadShells[@]}"; do
    [[ -e "${file}" ]] && source "${file}"
done

# CurrentDir
ScriptDir="$(readlinkf "${0}")"
