#!/usr/bin/env bash

set -Eeu

QctlLibDir="%LIB_DIR%"
LoadShells=("${QctlLibDir}/main.sh")

# Load main library
for file in "${LoadShells[@]}"; do
    [[ -e "${file}" ]] && source "${file}"
done

# CurrentDir
ScriptDir="$(readlinkf)"

echo "${ScriptDir}"
