#!/usr/bin/env bash
%COMMON_CODE%

HelpDoc(){
    echo "usage qctl-add [option] [Type] [Name or Path] [Type Options]"
    echo
    echo "Add new virtual machine or new disk" 
    echo " Type:"
    echo "    Disk                     Add disk to datebase"
    echo "    VM                       Add new virtual machine"
    echo
    echo "Disk Options:"
    echo "    CD                       Set image as CD"
    echo
    echo " General options:"
    echo "    -h | --help              This help message"
}

Main(){
    case "${Type}" in
        "vm")
            CreateNewVM "${Name}" "${@}"
            ;;
        "disk")
            #local _DiskType="${1-""}"
            AddNewDisk "${Name}" "${@}"
            MsgInfo "Add ${Name} as $(GetDiskUUIDPathFromPath "${Name}")"
            ;;
    esac
}

# Parse options
OPTS=("h") OPTL=("help")
ParseCmdOpt SHORT="$(printf "%s" "${OPTS[@]}")" LONG="$(printf "%s," "${OPTL[@]}")" -- "${@}" || exit 1
eval set -- "${OPTRET[@]}"
unset OPTRET OPTS OPTL

while true; do
    case "${1}" in
        -h | --help)
            HelpDoc
            exit 0
            ;;
        --)
            shift 1
            break
            ;;
        *)
            MsgError "Argument exception error '${1}'"
            MsgError "Please report this error to the developer." 1
            ;;
    esac
done

Type="${1-""}"
Name="${2-""}"

[[ -z "${Name}" ]] || shift 1
[[ -z "${Type}" ]] || shift 1

Main "${@}"
